main.py
from flask import Flask, render_template, send_from_directory, request, redirect, url_for
from flask_cors import CORS
from flask import Flask, render_template, request, jsonify, session
from routes.wep import defaultAPI
from dotenv import load_dotenv
import os

load_dotenv()


app = Flask(__name__)
CORS(app)
app.template_folder = 'templates'
app.static_folder = 'static'
app.secret_key = os.getenv("PRIVATE_KEY")


app.register_blueprint(defaultAPI, url_prefix='/')

if __name__ == '__main__':
    app.run(debug=True)
    # app.run(host=os.getenv('HOST'), port=int(os.getenv('PORT')), debug=True)

routes/__init__.py
from flask import Blueprint

defaultAPI = Blueprint('defaultAPI', __name__)

from . import wep

routes/wep.py
from . import defaultAPI
from flask import  jsonify, render_template, request, session, redirect, url_for, send_file, send_from_directory
from config.db import db
from PIL import Image
import base64
from io import BytesIO
import torch
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


Classes = ['Uninfected_Patients', 'Plasmodium_falciparum', 'Plasmodium_Vivax']

class VGGModel(torch.nn.Module):
    def __init__(self):
        super(VGGModel, self).__init__()

    def forward(self, x):
        pass

@defaultAPI.route('/testapi', methods=['GET'])
def api_entry():
    response = {
        'status': 200,
        'model_status': 'Model loaded successfully!',
        'data': "API Running",
    }
    return jsonify(response)


@defaultAPI.route('/')
def index():
    return render_template('index.html' , title='Home')
@defaultAPI.route('/about')
def about():
    return render_template('aboutus.html' , title='About Us')
@defaultAPI.route('/tutorial')
def tutorial():
    return render_template('tutorial.html' , title='Tutorial')


@defaultAPI.route('/upload', methods=['POST'])
def upload():


    if 'file' not in request.files:
        return render_template('index.html', error='No file part')

    file = request.files['file']

    if file.filename == '':
        return render_template('index.html', error='No selected file')

    model_path = './Maraliavgg16.pt'  
    model = torch.jit.load(model_path, map_location=torch.device('cpu'))
    model.eval()
    print("Model loaded successfully!")

    image = Image.open(file)
    image2 = Image.open(file)

    single_image_transform = transforms.Compose([
        transforms.Resize((100, 100)),
        transforms.ToTensor(),
    ])
    transformed_image = single_image_transform(image)

    transformed_image = transformed_image.unsqueeze(0)

    outputs = model(transformed_image)
    _, predicted = torch.max(outputs, 1)

    image = transformed_image.squeeze().cpu().permute(1, 2, 0).numpy()
    predicted_label = predicted.item()
    predicted_class_name = Classes[predicted_label]

    buffered = BytesIO()
    image2.save(buffered, format="JPEG")
    img_str = base64.b64encode(buffered.getvalue()).decode('utf-8')

    return render_template('result.html', img=img_str, predicted_class=predicted_class_name, title='Result')

@defaultAPI.route('/img/<filename>')
def send_img(filename):
    return send_from_directory('./static/img', filename)
@defaultAPI.route('/robots.txt')
def send_robots():
    return send_from_directory('./static', 'robots.txt')

@defaultAPI.errorhandler(404)
def page_not_found(e):
    return redirect(url_for('index'))

templates/aboutus.html
{% extends 'layout.html' %}

 {% block header %} 
 {% include 'nav.html' %} {%
endblock %}
 {% block content %}

<div
  class="container d-flex justify-content-center vh-100 text-center p-4 mt-4 flex-column"
>
  <h1>เกี่ยวกับเรา</h1>

</div>
{% endblock %} {% block footer %} {% include 'footer.html' %} {% endblock %}

templates/footer.html
<!-- Section: Social media -->
<section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Right -->
    <div>
        <a href="" class="me-4 text-reset">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
            <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
            <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
            <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
            <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
            <i class="fab fa-github"></i>
        </a>
    </div>
    <!-- Right -->
</section>
<section class="d-none d-lg-block d-md-block ">
    <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4 ">
                <!-- Content -->
                <img loading="lazy" src="{{ url_for('static', filename='img/Red_0.png') }}" width="243"
                    alt="Meat Avatar logo" class="d-inline-block align-text-top" aria-hidden="true">
                <div class="d-flex flex-row gap-3 my-4">
                    <img loading="lazy" src="{{ url_for('static', filename='img/socials/socials_2.png') }}"
                        alt="Facebook">
                    <img loading="lazy" src="{{ url_for('static', filename='img/socials/socials_3.png') }}" alt="Line">
                    <img loading="lazy" src="{{ url_for('static', filename='img/socials/socials_4.png') }}"
                        alt="Instagram">
                    <img loading="lazy" src="{{ url_for('static', filename='img/socials/socials_1.png') }}"
                        alt="Tiktok">
                </div>
            </div>
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <p>
                    <a href="#!" class="text-reset" alt="our product">Our product</a>
                </p>
                <p>
                    <a href="#!" class="text-reset" alt="how to order">How to order</a>
                </p>
                <p>
                    <a href="#!" class="text-reset" alt="why meat avatar?">Why Meat Avatar?</a>
                </p>
                <p>
                    <a href="#!" class="text-reset" alt="Sustainability">Sustainability</a>
                </p>
                <p>
                    <a href="#!" class="text-reset" alt="faq">FAQ</a>
                </p>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <p>
                    <a href="#!" class="text-reset" alt="about">About</a>
                </p>
                <p>
                    <a href="#!" class="text-reset" alt="our mission">Our mission</a>
                </p>
                <p>
                    <a href="#!" class="text-reset" alt="Planted-base for better world">Planted-base for better
                        world</a>
                </p>
                <p>
                    <a href="#!" class="text-reset" alt="contact">Contact us</a>
                </p>
            </div>

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4 d-flex justify-content-center flex-column">
       
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
    </div>
</section>
<!-- Copyright -->
<div class="container text-center p-4 d-flex justify-content-between " style="border-top: 1px solid #f1f1f1;">
    <a href="#" class="darkhc">#Better Meat for Better World</a>
    <div class="darkhc">
        <span>Copyright © 2023 Meat Avatar</span>
        <span class="mx-2">Powered by Meat Avatar</span>
    </div>
</div>

templates/index.html
<!-- templates/index.html -->

{% extends 'layout.html' %}


{% block header %}
  {% include 'nav.html' %}
{% endblock %}

{% block content %}
{% if error %}
<div class="alert alert-danger" role="alert">
    {{ error }}
</div>
{% endif %}
<div class="container d-flex justify-content-center align-items-center text-center flex-column vh-100">
  <h1>ระบบวินิฉัยโรคมาลาเรีย</h1>
  <p>ยินดีต้อนรับสู่ระบบวินิฉัยโรคมาลาเรีย</p>
    <form action="{{ url_for('defaultAPI.upload') }}" method="POST" enctype="multipart/form-data" class="d-flex gap-4">
      <input type="file" name="file" accept="image/*" class="form-control border-2 border-warning">
      <input type="submit" value="วินิฉัย" class="btn btn-warning fw-bold text-white">
    </form>
</div>


{% endblock %}

{% block footer %}
  {% include 'footer.html' %}
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="language" content="English" />

    <link
      rel="icon"
      href="{{ url_for('static', filename='img/favicon.png') }}"
      sizes="192x192"
      alt="Meat Avatar Icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      type="text/css"
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <link
      type="text/css"
      rel="stylesheet"
      href="{{ url_for('static', filename='css/base.css') }}"
    />

    <title>{{ title }}</title>
  </head>

  <body>
    <div class="overlay">
      <div class="loader"></div>
    </div>

    <header>
      {% include 'nav.html' %}
    </header>

    <main class="min-vh-100">
      {% block content %}
      {% endblock %}
    </main>

    <footer class="text-center text-lg-start bg-body-tertiary text-muted">
    </footer>
  </body>

  <script async src="{{ url_for('static', filename='js/script.js') }}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"
  ></script>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg py-2 sticky-nav" style="z-index: 9999;">
    <div class="container-fluid px-4">

        <button class="navbar-toggler w-100 d-flex justify-content-between d-lg-none " type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
            aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <svg xmlns="http://www.w3.org/2000/svg" height="30" width="30" viewBox="0 0 448 512">
                <path fill="#4b1212"
                    d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z" />
            </svg>
            <span class="navbar-toggler-icon"></span>
            <img loading="lazy" src="{{ url_for('static', filename='img/favicon.png') }}" width="50" alt="Meat Avatar Logo"
                class="d-inline-block align-text-top" aria-hidden="true">
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <div class="d-none d-lg-block">
                <img loading="lazy" src="{{ url_for('static', filename='img/favicon.png') }}" width="50" alt="Meat Avatar Logo"
                    class="d-inline-block align-text-top" aria-hidden="true" >
            </div>

            <ul class="navbar-nav mx-auto mb-2 mb-lg-0 gap-2 gap-lg-4 gap-md-4">
                <li class="nav-item">
                    <a class="nav-link fw-bold text-dark" href="/" >Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fw-bold text-dark" href="/tutorial">วิธีการใช้งาน</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fw-bold text-dark" href="/about" >เกี่ยวกับ</a>
                </li>
            </ul>

            <ul class="navbar-nav my-2">
                <li class="nav-item d-flex px-0 px-lg-3 px-md-3">
                    <a type="button" class="btn buy-btn" href="#" aria-label="Buy">...</a>
                </li>
            </ul>

        </div>
    </div>
</nav>

templates/result.html
<!-- templates/result.html -->
{% extends 'layout.html' %}

 {% block header %} 
 {% include 'nav.html' %} {%
endblock %}
 {% block content %}

<div
  class="container d-flex justify-content-center vh-100 text-center p-4 mt-4 flex-column"
>
  <h1>ผลการวินิจฉัย</h1>
  <div class="row my-4">
    <div class="col-6">
      <img
        src="data:image/jpeg;base64,{{ img }}" 
        width="300"
        class="shadow-sm"
        height="auto"
        alt="Uploaded Image"
      />
    </div>
    <div class="col-6">
      <p class="text-start">
        {{predicted_class }}
      </p>
    </div>
  </div>
</div>
{% endblock %} {% block footer %} {% include 'footer.html' %} {% endblock %}

templates/section-top.html
<section class="section-top my-4 p-lg-2 p-md-2 p-4">

    <div class="row ">
     
    </div>
</section>

templates/tutorial.html
{% extends 'layout.html' %}

 {% block header %} 
 {% include 'nav.html' %} {%
endblock %}
 {% block content %}

<div
  class="container d-flex justify-content-center vh-100 text-center p-4 mt-4 flex-column"
>
  <h1>วิธีการใช้</h1>

</div>
{% endblock %} {% block footer %} {% include 'footer.html' %} {% endblock %}